name: BuildAndTest
on: [push]
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - run: ls
      - run: cd "${{ github.workspace }}/03_Implementation"
      - run: ls
      - run: cd JujuBot_uC_A8
      
      - run: mkdir "${{ github.workspace }}/03_Implementation/JujuBot_uC_A8/JujuBot_uC_A8/build"
      - run: cd "${{ github.workspace }}/03_Implementation/JujuBot_uC_A8/JujuBot_uC_A8/build"
      - run: cmake ..
      - run: make 
      - run: make test
      - run: gcc --version
      - run: python --version
