name: BuildAndTest
on: [push]
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: apt-get install doygen -y

      - run: mkdir "${{ github.workspace }}/03_Implementation/JujuBot_uC_A8/JujuBot_uC_A8/build"
      - run: cmake -B "${{ github.workspace }}/03_Implementation/JujuBot_uC_A8/JujuBot_uC_A8/build" -S "${{ github.workspace }}/03_Implementation/JujuBot_uC_A8/JujuBot_uC_A8"
      - run: make "${{ github.workspace }}/03_Implementation/JujuBot_uC_A8/JujuBot_uC_A8/build"
#      - run: make test
      - run: gcc --version
      - run: python --version
